/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emergencyEnterprise;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.sun.jdi.connect.spi.Connection;
import emergencyEnterprise.emergency.Model.Police;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bharg
 */
public class policeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form policeAdmin
     */
    public policeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        policeTable = new javax.swing.JTable();
        designationTxt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        genderTxt = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        addTxt = new javax.swing.JButton();
        salaryTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabellogoaddpolice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        policeTableD = new javax.swing.JTable();
        viewDBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        viewBEBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        professorTable = new javax.swing.JTable();
        viewSBtn = new javax.swing.JButton();
        viewPBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnStudLogout = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 102));
        jTabbedPane1.setForeground(new java.awt.Color(242, 242, 242));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        policeTable.setBackground(new java.awt.Color(0, 0, 51));
        policeTable.setForeground(new java.awt.Color(255, 255, 255));
        policeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Phone", "Age", "Salary", "Designation"
            }
        ));
        policeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(policeTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 239, 779, 197));

        designationTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Major ", "Sergeant", "CBI", "Officer" }));
        jPanel1.add(designationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 86, 150, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 131, 49, 17));

        updateBtn.setBackground(new java.awt.Color(255, 255, 0));
        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 75, 23));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Name:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 95, 40, 20));
        jPanel1.add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 198, 150, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Phone:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 166, 44, 17));
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 94, 150, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Age:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 201, 28, 17));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Salary:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 60, 17));

        genderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 128, 150, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Designation:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 78, 17));
        jPanel1.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 163, 150, -1));

        addTxt.setBackground(new java.awt.Color(255, 255, 0));
        addTxt.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        addTxt.setText("Add");
        addTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtActionPerformed(evt);
            }
        });
        jPanel1.add(addTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 80, 23));
        jPanel1.add(salaryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 198, 150, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD POLICE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 202, 36));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 71, 17));
        jPanel1.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 119, 151, -1));
        jPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 157, 151, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 66, 17));

        viewBtn.setBackground(new java.awt.Color(255, 255, 0));
        viewBtn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, -1, 23));

        deleteBtn.setBackground(new java.awt.Color(255, 255, 0));
        deleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, 23));

        jLabellogoaddpolice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDnobg.png"))); // NOI18N
        jPanel1.add(jLabellogoaddpolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDbg.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        jTabbedPane1.addTab("Add Police", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailsTable.setBackground(new java.awt.Color(0, 0, 51));
        detailsTable.setForeground(new java.awt.Color(255, 255, 255));
        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "Address", "Crime Details", "Officer Name", "Action Taken"
            }
        ));
        jScrollPane2.setViewportView(detailsTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 131, 652, 294));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crime Details");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 140, 32));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        searchTxt.setForeground(new java.awt.Color(153, 0, 0));
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtKeyPressed(evt);
            }
        });
        jPanel2.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 90, 217, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 93, 53, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDnobg.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 90));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDbg.jpg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Complaint Records", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        policeTableD.setBackground(new java.awt.Color(0, 0, 51));
        policeTableD.setForeground(new java.awt.Color(255, 255, 255));
        policeTableD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Age", "Phone", "Salary", "Designation"
            }
        ));
        policeTableD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policeTableDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(policeTableD);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 65, 424, 155));

        viewDBtn.setBackground(new java.awt.Color(255, 255, 0));
        viewDBtn.setText("View");
        viewDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewDBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        employeeTable.setBackground(new java.awt.Color(0, 0, 51));
        employeeTable.setForeground(new java.awt.Color(255, 255, 255));
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Age", "Phone"
            }
        ));
        jScrollPane4.setViewportView(employeeTable);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 65, 403, 155));

        viewBEBtn.setBackground(new java.awt.Color(255, 255, 0));
        viewBEBtn.setText("View");
        viewBEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBEBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewBEBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        studentTable.setBackground(new java.awt.Color(0, 0, 51));
        studentTable.setForeground(new java.awt.Color(255, 255, 255));
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Age"
            }
        ));
        jScrollPane5.setViewportView(studentTable);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 424, 142));

        professorTable.setBackground(new java.awt.Color(0, 0, 51));
        professorTable.setForeground(new java.awt.Color(255, 255, 255));
        professorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Age"
            }
        ));
        jScrollPane6.setViewportView(professorTable);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 403, 142));

        viewSBtn.setBackground(new java.awt.Color(255, 255, 0));
        viewSBtn.setText("View");
        viewSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewSBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        viewPBtn.setBackground(new java.awt.Color(255, 255, 0));
        viewPBtn.setText("View");
        viewPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewPBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Police");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bank Employee");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 16));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Professor");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Student");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDbg.jpg"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        jTabbedPane1.addTab("Documentation", jPanel3);

        jPanel4.setLayout(null);

        btnStudLogout.setBackground(new java.awt.Color(255, 255, 0));
        btnStudLogout.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnStudLogout.setText("Logout");
        btnStudLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudLogoutActionPerformed(evt);
            }
        });
        jPanel4.add(btnStudLogout);
        btnStudLogout.setBounds(410, 340, 72, 22);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPD-login logo.png"))); // NOI18N
        jPanel4.add(jLabel19);
        jLabel19.setBounds(377, 108, 140, 200);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("End Current Session?");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(380, 310, 140, 17);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDbg.jpg"))); // NOI18N
        jPanel4.add(jLabel20);
        jLabel20.setBounds(0, 0, 900, 510);

        jTabbedPane1.addTab("Action", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String policeUsername = "";
    private void policeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel profModel = (DefaultTableModel) policeTable.getModel();
        String PnameTxt = policeTable.getValueAt(policeTable.getSelectedRow(), 0).toString();
        nameTxt.setText(PnameTxt);
        genderTxt.setSelectedItem(policeTable.getValueAt(policeTable.getSelectedRow(), 1).toString());
        phoneTxt.setText(policeTable.getValueAt(policeTable.getSelectedRow(), 2).toString());
        ageTxt.setText(policeTable.getValueAt(policeTable.getSelectedRow(), 3).toString());
        salaryTxt.setText(policeTable.getValueAt(policeTable.getSelectedRow(), 4).toString());
        designationTxt.setSelectedItem(policeTable.getValueAt(policeTable.getSelectedRow(), 5).toString());

        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            String profQuery = "SELECT username, password FROM police WHERE name = ?";
            java.sql.PreparedStatement statement = connection.prepareStatement(profQuery);
            statement.setString(1, PnameTxt);

            java.sql.ResultSet profData = statement.executeQuery();
            if (profData.next()) {
                policeUsername = profData.getString("username");
                usernameTxt.setText(policeUsername);
                passwordTxt.setText(profData.getString("password"));
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_policeTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String Name = nameTxt.getText();
        String Gender = (String) genderTxt.getSelectedItem();
        String phone = phoneTxt.getText(); // Keep phone as String
        int age;
        double salary; // Use double for salary
        String Designation = (String) designationTxt.getSelectedItem();
        String username = usernameTxt.getText();
        String password = passwordTxt.getText();

        // Validate inputs
        try {
            age = Integer.parseInt(ageTxt.getText());
            salary = Double.parseDouble(salaryTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Age or Salary. Please enter numeric values.");
            return;
        }

        if (policeUsername.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a police officer to update!");
            return;
        }

        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            String updateQuery = "UPDATE police SET name = ?, gender = ?, phone = ?, age = ?, salary = ?, designation = ?, username = ?, password = ? WHERE username = ?";
            java.sql.PreparedStatement statement = connection.prepareStatement(updateQuery);
            statement.setString(1, Name);
            statement.setString(2, Gender);
            statement.setString(3, phone);
            statement.setInt(4, age);
            statement.setDouble(5, salary);
            statement.setString(6, Designation);
            statement.setString(7, username);
            statement.setString(8, password);
            statement.setString(9, policeUsername);

            int rowsAffected = statement.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Police details updated successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to update police details!");
            }
            connection.close();
            refreshPoliceTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }


    }//GEN-LAST:event_updateBtnActionPerformed


    private void addTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtActionPerformed
        // TODO add your handling code here:

        String name = nameTxt.getText();
        String gender = genderTxt.getSelectedItem().toString();
        String phone = phoneTxt.getText(); // Keep phone as String
        String username = usernameTxt.getText();
        String password = passwordTxt.getText();
        int age;
        double salary; // Use double for salary
        String designation = (String) designationTxt.getSelectedItem();

        // Validate inputs
        try {
            age = Integer.parseInt(ageTxt.getText());
            salary = Double.parseDouble(salaryTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Age or Salary. Please enter numeric values.");
            return;
        }

        if (username.isEmpty() || name.isEmpty() || phone.isEmpty() || designation.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all required details!");
            return;
        }

        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            String insertQuery = "INSERT INTO police (name, gender, phone, age, salary, designation, username, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement statement = connection.prepareStatement(insertQuery);
            statement.setString(1, name);
            statement.setString(2, gender);
            statement.setString(3, phone);
            statement.setInt(4, age);
            statement.setDouble(5, salary);
            statement.setString(6, designation);
            statement.setString(7, username);
            statement.setString(8, password);

            statement.execute();
            JOptionPane.showMessageDialog(null, "New police officer added successfully!");
            connection.close();

            // Clear inputs
            nameTxt.setText("");
            phoneTxt.setText("");
            ageTxt.setText("");
            salaryTxt.setText("");
            usernameTxt.setText("");
            passwordTxt.setText("");
            genderTxt.setSelectedItem("");
            designationTxt.setSelectedItem("");
            refreshPoliceTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_addTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel) detailsTable.getModel();
        tb1Model.setRowCount(0);
        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.crimedetails";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while (studentData.next()) {
                String name = studentData.getString("name");
                String phone = studentData.getString("phone");
                String address = studentData.getString("address");
                String crimeDetails = studentData.getString("crimeDetails");
                String officer = studentData.getString("officer");
                String action = studentData.getString("action");

                String tbData[] = {name, phone, address, crimeDetails, officer, action};

                tb1Model.addRow(tbData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) detailsTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        detailsTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTxt.getText().trim()));
    }//GEN-LAST:event_searchTxtKeyPressed

    private void policeTableDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeTableDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_policeTableDMouseClicked

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel) policeTable.getModel();
        tb1Model.setRowCount(0);
        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.police";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while (studentData.next()) {
                String name = studentData.getString("name");
                String gender = studentData.getString("gender");
                String phone = studentData.getString("phone");
                String age = studentData.getString("age");
                String salary = studentData.getString("salary");
                String designation = studentData.getString("designation");

                String tbData[] = {name, gender, phone, age, salary, designation};

                tb1Model.addRow(tbData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void viewBEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBEBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel) employeeTable.getModel();
        tb1Model.setRowCount(0);
        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.bankemployee";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while (studentData.next()) {
                //String id = studentData.getString("Id");
                String name = studentData.getString("Name");
                String gender = studentData.getString("Gender");
                String phone = studentData.getString("Phone");
                String age = studentData.getString("Age");
                // String salary = studentData.getString("Salary");
                // String accountType = studentData.getString("AccountType");

                String tbData[] = {name, gender, phone, age};

                tb1Model.addRow(tbData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_viewBEBtnActionPerformed

    private void viewDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel) policeTableD.getModel();
        tb1Model.setRowCount(0);
        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.police";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while (studentData.next()) {
                String name = studentData.getString("name");
                String gender = studentData.getString("gender");
                String phone = studentData.getString("phone");
                String age = studentData.getString("age");
                String salary = studentData.getString("salary");
                String designation = studentData.getString("designation");

                String tbData[] = {name, gender, phone, age, salary, designation};

                tb1Model.addRow(tbData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_viewDBtnActionPerformed

    private void viewSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel) studentTable.getModel();
        tb1Model.setRowCount(0);
        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.students";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while (studentData.next()) {
                String name = studentData.getString("Name");
                String email = studentData.getString("Email");

                String age = studentData.getString("Age");

                String tbData[] = {name, email, age};

                tb1Model.addRow(tbData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_viewSBtnActionPerformed

    private void viewPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel) professorTable.getModel();
        tb1Model.setRowCount(0);
        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.professors";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while (studentData.next()) {
                String name = studentData.getString("Name");
                String email = studentData.getString("Email");

                String age = studentData.getString("Age");

                String tbData[] = {name, email, age};

                tb1Model.addRow(tbData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }

    }//GEN-LAST:event_viewPBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if (policeUsername.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a police officer to delete!");
            return;
        }

        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
            String deleteQuery = "DELETE FROM police WHERE username = ?";
            java.sql.PreparedStatement statement = connection.prepareStatement(deleteQuery);
            statement.setString(1, policeUsername);

            int rowsAffected = statement.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Police officer deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete police officer!");
            }
            connection.close();

            // Clear inputs
            nameTxt.setText("");
            phoneTxt.setText("");
            ageTxt.setText("");
            salaryTxt.setText("");
            usernameTxt.setText("");
            passwordTxt.setText("");
            genderTxt.setSelectedItem("");
            designationTxt.setSelectedItem("");
            refreshPoliceTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void btnStudLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudLogoutActionPerformed
        // TODO add your handling code here:
        emergencyLogin emergencyLoginObj = new emergencyLogin();
        setVisible(false);
        emergencyLoginObj.setVisible(true);
    }//GEN-LAST:event_btnStudLogoutActionPerformed

    public void police_table() {
        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");

            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String sql = "SELECT * FROM universitysystem.police;";
            // statement.executeUpdate("insert into hospitalsystem.login" + "(role, username, password)" + "values ('"+role+"','"+username+"', '"+password+"')");
            //JOptionPane.showMessageDialog(null, "User successfully added!");
            java.sql.ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                String id = rs.getString("id");
                String name = rs.getString("name");
                String gender = rs.getString("gender");
                String age = rs.getString("age");
                String phone = rs.getString("phone");
                String salary = rs.getString("salary");
                String designation = rs.getString("designation");

                String tbData[] = {id, name, gender, age, phone, salary, designation};
                DefaultTableModel tb1Model = (DefaultTableModel) policeTable.getModel();

                tb1Model.addRow(tbData);
                System.out.println("Ashish well done");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "please add data in correct format!");
        }
    }
    private void refreshPoliceTable() {
    DefaultTableModel tb1Model = (DefaultTableModel) policeTable.getModel();
    tb1Model.setRowCount(0); // Clear existing rows

    try {
        java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user1234");
        java.sql.Statement statement = connection.createStatement();
        String fetchQuery = "SELECT * FROM police";
        java.sql.ResultSet rs = statement.executeQuery(fetchQuery);

        while (rs.next()) {
            String name = rs.getString("name");
            String gender = rs.getString("gender");
            String phone = rs.getString("phone");
            String age = rs.getString("age");
            String salary = rs.getString("salary");
            String designation = rs.getString("designation");

            String tbData[] = {name, gender, phone, age, salary, designation};
            tb1Model.addRow(tbData);
        }
        connection.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error refreshing table: " + e.getMessage());
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(policeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(policeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(policeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(policeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new policeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTxt;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton btnStudLogout;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<String> designationTxt;
    private javax.swing.JTable detailsTable;
    private javax.swing.JTable employeeTable;
    private javax.swing.JComboBox<String> genderTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabellogoaddpolice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTable policeTable;
    private javax.swing.JTable policeTableD;
    private javax.swing.JTable professorTable;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JButton viewBEBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton viewDBtn;
    private javax.swing.JButton viewPBtn;
    private javax.swing.JButton viewSBtn;
    // End of variables declaration//GEN-END:variables
}
